version: '3.9'

networks:
  mi-red:

services:

  config-server:
    build: ./servidor-configuracion
    restart: always
    environment:
      - EUREKA_SERVER=eureka-server
      - spring_profiles_active=nube
      - LOGSTASH_SERVER=logstash
    ports:
      - 8888:8888
    networks:
      - mi-red

  eureka-server:
    build: ./servidor-eureka
    restart: always
    environment:
      - CONFIG_SERVER=config-server
      - LOGSTASH_SERVER=logstash
    ports:
      - 8761:8761
    networks:
      - mi-red
    depends_on:
      - config-server

  zulu-server:
    build: ./servidor-perimetral
    restart: always
    environment:
      - CONFIG_SERVER=config-server
      - EUREKA_SERVER=eureka-server
      - LOGSTASH_SERVER=logstash
    ports:
      - 8081:8081
    networks:
      mi-red:
    depends_on:
      - eureka-server


  base-datos-user:
    image: oscarfonts/h2
    restart: always
    environment:
      - H2_OPTIONS=-ifNotExists
    ports:
      - 8082:81
    networks:
      - mi-red

  microservicio-user:
    build: ./users-microservice
    restart: always
    environment:
      - CONFIG_SERVER=config-server
      - HOST_BD=base-datos-user
      - EUREKA_SERVER=eureka-server
      - LOGSTASH_SERVER=logstash
      - PUERTO_DB=1521
      - NOMBRE_DB=~./userdb
    networks:
      - mi-red
    depends_on:
      - base-datos-user

  microservicio-pack:
    build: ./pack-microservice
    restart: always
    environment:
      - CONFIG_SERVER=config-server
      - HOST_BD=base-datos-user
      - EUREKA_SERVER=eureka-server
      - LOGSTASH_SERVER=logstash
      - PUERTO_DB=1521
      - NOMBRE_DB=~./packdb
    networks:
      - mi-red
    depends_on:
      - base-datos-user

  microservicio-purchase:
    build: ./packPurchases-microservice
    restart: always
    environment:
      - CONFIG_SERVER=config-server
      - HOST_BD=base-datos-user
      - EUREKA_SERVER=eureka-server
      - LOGSTASH_SERVER=logstash
      - PUERTO_DB=1521
      - NOMBRE_DB=~./packPurchasesdb
    networks:
      - mi-red
    depends_on:
      - base-datos-user

  microservicio-notificaciones:
    build: ./notificaciones-microservice
    restart: always
    environment:
      - CONFIG_SERVER=config-server
      - EUREKA_SERVER=eureka-server
      - LOGSTASH_SERVER=logstash
    networks:
      - mi-red
    depends_on:
      - base-datos-user

  client-web:
    build: ./cliente-microservice
    restart: always
    environment:
      - CONFIG_SERVER=config-server
      - EUREKA_SERVER=eureka-server
      - LOGSTASH_SERVER=logstash
    ports:
      - 8181:8181
    networks:
      - mi-red
    depends_on:
      - microservicio-user
      - zulu-server
      - microservicio-pack
#      - microservicio-purchase






